### ISSUE TITLE
EOD To-Do List May 9

### ISSUE THREAD

**Issue by lucyrose93** [yvonne-liu/FAC-Hardware#84]
- [ ] Front end testing
- [ ] Finalise app pages with copy and styling
- [ ] Post a test word on LED display "Hello World" from Node
- [ ] Start neatening css file
Stretch: 
- [ ] Turn LED display into app
